name: python-django

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install dependencies
      run:
        python -m pip install
        pip install django pillow gunicorn python-decouple psycopg2-binary django-environ
    - name: python-django
      run: |
         python manage.py
    - name: Build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
         image: testagon/python-django
         registry: docker.io
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Deploy to Server
      run: |
        chmod 600 ssh_key
        eval "$(ssh-agent -s)"
        ssh-add ssh_key
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-87-225-168.compute-1.amazonaws.com "cd /home/ubuntu/django-docker-main && git pull origin main"
    - env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      
