name: python-django

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install dependencies
      run:
        python -m pip install
        pip install django pillow gunicorn python-decouple psycopg2-binary django-environ
    - name: python-django
      run: |
         python manage.py
    - name: Build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
         image: testagon/python-django
         registry: docker.io
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
